openapi: 3.0.1
info:
  title: G-LAW 語氣憲法 API
  description: 調用語氣憲法條文的 API，支援 .exec(T-XX) 指令查詢
  version: '1.0.0'
servers:
  - url: https://light-infinity.vercel.app

paths:
  /api/execmap:
    get:
      summary: 查詢特定條文
      operationId: getByCode
      parameters:
        - name: code
          in: query
          required: false
          schema:
            type: string
          description: 條文代號（如 T-06）
      responses:
        '200':
          description: 回傳條文或條文列表